# Cấu hình cho build
[build]
  # Thư mục chứa các Netlify Functions
  functions = "netlify/functions"
  # Lệnh để build ứng dụng
  command = "npm run build"
  # Thư mục chứa kết quả sau khi build
  publish = "dist"

# Quy tắc chuyển hướng cho ứng dụng trang đơn (SPA)
[[redirects]]
  # Chuyển hướng tất cả các đường dẫn...
  from = "/*"
  # ...về file index.html
  to = "/index.html"
  # Với mã trạng thái 200 (OK), để React Router có thể xử lý
  status = 200